project_id = "pbosggnpdzrirjhuswkj"

[functions.public-tft-profile]
verify_jwt = false

[functions.public-tft-history]
verify_jwt = false

[functions.public-tft-match]
verify_jwt = false

# Deployment sync trigger: 2026-09-27

[functions.public-tft-meta]
verify_jwt = false
